# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./ml_model /app

# COpy the shared utils folder
COPY ./shared_utils .

# Delete model files
RUN rm -rf /app/mlruns

# Install psycopg2-binary
RUN pip install psycopg2-binary

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5002 available to the world outside this container
EXPOSE 5002

# Run app.py when the container launches
CMD ["python", "ml_model.py"]
